server:
  port: 8203


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: APPOINTMENT-SERVICE
#                fallbackuri: forward:/userServiceFallBack
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackuri: forward:/departmentServiceFallBack
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: DEPARTMENT-SERVICE
        #                fallbackuri: forward:/departmentServiceFallBack

